# @package _global_
defaults:
  - override /dataset: OrganAMNIST
  - _self_


device:
  cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  id: 7

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: 061901_OrganA|
# ===========================

clip:
  templete_prompts: [
    'a photo of a {}.'
    ]
