# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  # cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  cuda_visible_devices:  "0,1,2,3"
  id: 2

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: 062007_cifar100_ctx16
# ===========================

clip:
  ctx_init: "a photo of a X X X X X X X X X X X X"
