# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  # cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  cuda_visible_devices:  "0,1,2,3"
  id: 0

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: 062001_cifar100_img2ref
# ===========================

clip:
  img_to_ref_enable: True