# @package _global_
defaults:
  - override /dataset: OrganAMNIST
  - _self_


device:
  # cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  cuda_visible_devices:  "0,1,2,3"
  id: 0

optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4

# ===========================
process_title: 062109_OrganA_sgd_img2ref_description
# ===========================

clip:
  img_to_ref_enable: True
  use_description_ref: True
  templete_prompts: [
    "a CT photo of a {}: A round or oval low-density structure located in the lower pelvic cavity.",
    "a CT photo of a {}: A long, bright white bone structure in the upper thigh.",
    "a CT photo of a {}: A long, bright white bone structure in the upper thigh.",
    "a CT photo of a {}: A characteristic heart-shaped organ in the central-left chest cavity.",
    "a CT photo of a {}: Bean-shaped organs with distinct cortex and medulla in the posterior abdominal wall.",
    "a CT photo of a {}: Bean-shaped organs with distinct cortex and medulla in the posterior abdominal wall.",
    "a CT photo of a {}: A large, homogeneous organ in the right upper abdomen with visible lobes and vessels.",
    "a CT photo of a {}: Low-density areas in the chest cavity with visible bronchi and blood vessels.",
    "a CT photo of a {}: Low-density areas in the chest cavity with visible bronchi and blood vessels.",
    "a CT photo of a {}: An elongated, slightly high-density structure across the upper abdomen.",
    "a CT photo of a {}: A crescent-shaped, homogeneous organ in the left upper abdomen."
    ]
