# @package _global_
defaults:
  - override /dataset: OrganAMNIST
  - _self_


device:
  # cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  cuda_visible_devices:  "0,1,2,3"
  id: 2

optimizer:
  _target_: torch.optim.SGD
  lr: 0.002
  momentum: 0.9
  weight_decay: 1e-4

scheduler_enable: True  
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${trainer.max_epochs}


# ===========================
process_title: 062106_OrganA_lrscheduler_E10_alpha01
# ===========================

trainer:
  max_epochs: 10

fl:
  dirichlet_alpha: 0.1
