# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  # cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  cuda_visible_devices:  "0,1,2,3"
  id: 3

optimizer:
  _target_: torch.optim.SGD
  lr: 1e-4
  momentum: 0.9
  weight_decay: 1e-4

# ===========================
process_title: 062401_cifar100_sgd_400R_Lr1e4
# ===========================

fl:
  round: 400

