# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  id: 6


optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: 15modify_test
# ===========================

logger:
  wandb_enable: False

fl:
  client_num: 20
  select_client_num: 2
  round: 2
  dirichlet_alpha: 0.01

trainer:
  max_epochs: 2

clip:
  ImageTextLoss: SupConLoss  # t2t_mseloss  SupConLoss  contrastive_loss
  TextTextLoss: SupConLoss  # t2t_mseloss  SupConLoss  contrastive_loss