# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_

# ===========================
process_title: AdamW|lr=1e-3
# ===========================

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 2e-6

device:
  id: 1