# configs/experiments/Experiment1.yaml
defaults:
  - ../base

device:
  id: 0

optimizer:
  _target_: torch.optim.SGD
  lr: 2e-3
  momentum: 0.9

logger:
  wandb_enable: False

# ===========================
process_title: exp_lr|SGD_Optim
# ===========================