# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_
  

device:
  id: 0

optimizer:
  _target_: torch.optim.SGD
  lr: 1e-2
  momentum: 0.9


# ===========================
process_title: exp_lr|lr=1e-2
# ===========================