# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_
  

device:
  id: 3

optimizer:
  _target_: torch.optim.SGD
  lr: 2e-4
  momentum: 0.9

logger:
  wandb_enable: True

# ===========================
process_title: exp_lr|SGD_Optim
# ===========================