# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  id: 3

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: modify_test
# ===========================

logger:
  wandb_enable: False

fl:
  client_num: 20
  select_client_num: 2
  round: 2
  dirichlet_alpha: 0.01

trainer:
  max_epochs: 2