# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  cuda_visible_devices:  "0,1,2,3,4,5,6,7"
  id: 6

optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4

# ===========================
process_title: sgd|DisableT2T
# ===========================

clip:
  text_to_text_enable: False
  templete_prompts: [
    'a photo of a {}.'
    ]
