# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_


device:
  id: 0

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: T2TLoss|0620disable_t2tLoss
# ===========================

clip:
  text_to_text_enable: False