# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_
  

device:
  id: 1

optimizer:
  _target_: torch.optim.SGD
  lr: 2e-3
  momentum: 0.9

clip:
  text_to_text_weight: 5


# ===========================
process_title: text_weight|text_weight=5
# ===========================