# @package _global_
defaults:
  - override /dataset: cifar100
  - _self_
  

device:
  id: 2

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

clip:
  text_to_text_weight: 0.5


# ===========================
process_title: text_weight|text_weight=0.5
# ===========================