defaults:
  - dataset: cifar100
  - _self_
  - Exp: exp_base

device:
  cuda_visible_devices:  "0,1,2,3"
  id: 0
  cuda: cuda:${device.id}  # cpu  cuda:${device.id}
  float32_matmul_precision: medium

trainer:
  _target_:  pytorch_lightning.Trainer
  _convert_: all
  max_epochs: 5
  log_every_n_steps: 1
  check_val_every_n_epoch: ${trainer.max_epochs}
  devices:
    - ${device.id}
  # devices: 1
  accelerator: 'gpu'  # 'gpu' 'cpu'
  enable_model_summary: false
  precision: bf16-mixed  # 16-mixed  bf16-mixed  32
  logger: False
  enable_checkpointing: False

optimizer:

scheduler_enable: False 

# ===========================
process_title: "default"
# ===========================

logger:
  name: ${process_title}
  project: '20240616'
  wandb_enable: True


fl:
  client_num: 20
  select_client_num: 15
  round: 100
  dirichlet_alpha: 0.01

mode: train
seed: 42

output_dir: outputs

clip:
  backbone: ViT-B/32
  use_mlp: True
  mlp_hiddenlayer_num: 2048
  ctx_init: "a photo of a"

  text_correction: True
  templete_prompts:
    - "a photo of a {}."

  text_to_text_enable: True
  text_to_text_weight: 1

  add_noise_for_anchors: True
  use_description_ref: False
  ImageTextLoss: contrastive_loss  # t2t_mseloss  SupConLoss  contrastive_loss
  TextTextLoss: contrastive_loss  # t2t_mseloss  SupConLoss  contrastive_loss
  loss_margin: 0.2

  img_to_ref_enable: False
  
  momentum_ref: False
  momentum_weight: 0.5

dtype: torch.float32