defaults:
  - dataset: cifar100
  - system: lasp
  - _self_

device:
  cuda_visible_devices:  "0,1,2,3"
  id: 0
  cuda: cuda:${device.id}  # cpu  cuda:${device.id}
  float32_matmul_precision: medium

trainer:
  _target_:  pytorch_lightning.Trainer
  _convert_: all
  max_epochs: 5
  log_every_n_steps: 1
  check_val_every_n_epoch: ${trainer.max_epochs}
  devices:
    - ${device.id}
  # devices: 1
  accelerator: 'gpu'  # 'gpu' 'cpu'
  enable_model_summary: false
  precision: bf16-mixed  # 16-mixed  bf16-mixed  32
  logger: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 2e-6

# ===========================
process_title: 20clients_15selected_alpha0.01_text2textW20
# ===========================

logger:
  name: ${process_title}
  project: '20240616'
  wandb_enable: True


fl:
  client_num: 20
  select_client_num: 15
  round: 400
  dirichlet_alpha: 0.01

mode: train
seed: 42

output_dir: outputs

clip:
  backbone: ViT-B/32
  mlp_hiddenlayer_num: 2048
  ctx_init: "a photo of a"

  text_correction: True
  templete_prompts: ["a photo of a"]

  text_to_text_enable: True
  text_to_text_weight: 1

dtype: torch.float32